// Auto-extracted snippets from the 2020/2024 Book of Discipline.
// Source: church-documents/documents/discipline/bod-2024.json (complete ¶1–¶2720).
// Regenerate rather than hand-edit. Snippets are trimmed for popover display.

export interface DisciplineSnippet {
  number: string;
  title: string;
  snippet: string;
}

export const disciplineSnippets: Record<string, DisciplineSnippet> = {
  "266": { number: "266", title: "Certified Lay Servant", snippet: "1. A certified lay servant is a professing member of a local church or charge, or a baptized participant of a recognized United Methodist collegiate ministry or other United Methodist ministry setting, who desires to serve the Church and who knows and is committed to Scripture and the doctrine, heritage, organization, and life of The…" },
  "267": { number: "267", title: "Certified Lay Speaker", snippet: "1. A certified lay speaker is a certified lay servant (or equivalent as defined by his or her central conference) whose call has been affirmed by the conference committee on Lay Servant Ministries or equivalent structure to serve the church in pulpit supply in accordance and compliance with ¶ 341.1. 2. The certified lay speaker serves by preaching the Word when requested by the pastor, district superintendent, or committee on Lay Servant Ministries…" },
  "268": { number: "268", title: "Certified Lay Minister", snippet: "1. A certified lay minister is a certified lay servant, certified lay missioner, or equivalent as defined by his or her central conference, who is called and equipped to conduct public worship, care for the congregation, assist in program leadership, develop new and existing faith communities, preach the Word, lead small groups, or…" },
  "310": { number: "310", title: "Candidacy and Certification for Licensed and Ordained Ministry", snippet: "The licensed or ordained ministry is recognized by The United Methodist Church as a called-out and set-apart ministry. Therefore, it is appropriate that those persons who present themselves as candidates for licensed or ordained ministry be examined regarding the authenticity of their call by God to set-apart ministry." },
  "311": { number: "311", title: "Appointment of Certified Candidates", snippet: "A certified candidate is eligible for appointment as a local pastor upon completion of License for Pastoral Ministry (¶ 315). Those appointed as local pastors are clergy members of the annual conference (¶ 602.1) and are no longer listed as certified candidates." },
  "315": { number: "315", title: "License for Pastoral Ministry", snippet: "All persons not ordained as elders or deacons who are appointed to preach and conduct divine worship and perform the duties of a pastor shall have a license for pastoral ministry." },
  "324": { number: "324", title: "Qualifications for Election to Provisional Membership", snippet: "A person shall be eligible for election to provisional membership in the annual conference by a three-fourths majority vote of the clergy session on recommendation of its Board of Ordained Ministry after meeting the following qualifications. 1." },
  "325": { number: "325", title: "Commissioning", snippet: "Commissioning is the act of the church that publicly acknowledges God’s call and the response, talents, gifts, and training of the candidate. The church invokes the Holy Spirit as the candidate is commissioned to be a faithful servant leader among the people, to lead the church in service, to proclaim the Word of God and to equip others…" },
  "329": { number: "329", title: "Ministry, Authority, and Responsibilities of Deacons in Full Connection", snippet: "1. Deacons are persons called by God, authorized by the Church, and ordained by a bishop to a lifetime ministry of Word, Service, Compassion, and Justice, to both the community and the congregation in a ministry that connects the two. Deacons exemplify Christian discipleship and create opportunities for others to enter into discipleship." },
  "330": { number: "330", title: "Requirements for Ordination as Deacon and Admission to Full Connection", snippet: "Provisional members who are applying for admission into full connection and who have been provisional members for at least two years following the completion of the educational requirements for ordination as a deacon specified in below may be admitted into membership in full connection in an annual conference by three-fourths majority…" },
  "332": { number: "332", title: "Ministry of an Elder", snippet: "Elders are ordained ministers who, by God’s grace, have completed their formal preparation and have been commissioned and served as a provisional member, have been found by the Church to be of sound learning, of Christian character, possessing the necessary gifts and evidence of God’s grace, and whose call by God to ordination has been…" },
  "333": { number: "333", title: "Elders in Full Connection", snippet: "1. Elders in full connection with an annual conference by virtue of their election and ordination are bound in special covenant with all the ordained elders of the annual conference. In the keeping of this covenant they perform the ministerial duties and maintain the ministerial standards established by those in the covenant." },
  "335": { number: "335", title: "Requirements for Admission to Full Connection and Ordination as Elder", snippet: "Provisional members who are candidates for full connection and ordination as elders and have been provisional members for at least two years may be admitted into membership in full connection in an annual conference and approved for elder’s ordination by three-fourths majority vote of the clergy members in full connection of the annual…" },
};
